#' MakeMyForests: A package for parameterizing SORTIE-ND from Forest Inventory 
#' and Analysis Data
#' 
#' This package was designed to help scientists use freely available Forest 
#' Inventory and Analysis data from the USDA Forest Service to parameterize 
#' models within SORTIE-ND.
#' 
#' @section MakeMyForests functions:
#'   
#'   \code{\link{bootMean}}: This function...
#'   
#'    \code{\link{bootSd}}: This function...
#'  
#'   \code{\link{doFxBySort}}: This function is a wrapper that performs another 
#'   function by a sorting variable. The concept is a bit like 
#'   \code{\link{aggregate}}, but is more appropriate when you need to refer to 
#'   more than one column for your calculation.
#'   
#'   \code{\link{getBoot}}: This function...
#'   
#'   \code{\link{getC1}}: This function...
#'  
#'  \code{\link{getCoefficients}}: This function...
#'  
#'  \code{\link{getH3}}: This function...
#'  
#'  \code{\link{predictYfromLin}}: This function...
#'  
#'  \code{\link{prepLightData}}: This function...
#'  
#'  \code{\link{pullSpeciesCodes}}: This function...
#'  
#'  \code{\link{pullTrees}}: This function...
#'  
#'  \code{\link{putChar}}: This function...
#'  
#'  \code{\link{readCSVs}}: This function...
#'  
#'  \code{\link{se}}: This function...
#'  
#'  \code{\link{unitConvert}}: This function...
#'  
#'   
#' @section MakeMyForests data:
#'   
#'   \code{\link{FullTreesCA}}: This dataset...
#'   
#'   \code{\link{RefSpecies}}: This dataset...
#'  
#'  \code{\link{TreesCA}}: This dataset...
#'  
#'   
#' @docType package
#' @name MakeMyForests
NULL
